spring.application.name=JpaPro25-Product-Inventory-Management-System-Version


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/JPADataNit
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#logger relted msg
logging.level.root=INFO
logging.level.com.nit=DEBUG
